jobs:
  mail_on_push:
    runs-on: ubuntu-lastest
    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server-port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject:  ${{github.event.head_commit.message}}
          body: ${{github.repository}}
          to: maksim.monada@gmail.com
          from: Github actions 